### ISSUE TITLE
Support IT, ES, CN, BR and Https

### ISSUE THREAD

**Issue by Julienh** [zendframework/ZendService_Amazon#57]
Hello,
Is it possible to add IT, ES, CN and BR countries please ?
http://docs.aws.amazon.com/AWSECommerceService/latest/DG/SOAPEndpoints.html
Thanks!

**Comment by Xerkus** [comment]
@demiankatz want to tackle this one?

**Comment by demiankatz** [comment]
@Xerkus, I'll look into it when time permits -- probably next week.

**Comment by demiankatz** [comment]
@Xerkus, I looked into this, but was not sure what action was actually needed. I'm not sure where the code is dealing with locale, etc. I can't find any references to SOAP endpoints, etc.

@Julienh, can you elaborate on which service(s) you are trying to connect to using these locales? What is failing? Is the problem that the library needs locale support implemented, or simply that some locales are missing from the supported list?

(Apologies if I'm asking any silly questions -- I use only a small portion of this library and have little knowledge of most of the functionality here).

**Comment by Xerkus** [comment]
Endpoints are provided in the link here, and in code they are at https://github.com/zendframework/ZendService_Amazon/blob/master/src/Amazon.php#L54
For https, i guess, extra constructor parameter will have to be introduced

**Comment by demiankatz** [comment]
Thanks, @Xerkus, sorry I missed that. I'll work on this when time permits!

**Comment by demiankatz** [comment]
Sorry for the delay -- please see https://github.com/zendframework/ZendService_Amazon/pull/70, which adds all currently supported country codes as well as HTTPS support. I implemented this in the most backward-compatible way possible, so URLs still default to HTTP, and the $_baseUriList property still contains HTTP URLs (with SSL being implemented through a str_replace).

If backward-compatibility were not a concern, I would prefer turning SSL on by default, and replacing $_baseUriList with $hostnameList, with the protocol being prepended in the constructor based on the $useSsl flag.

**Comment by Julienh** [comment]
Thank you :)

**Comment by demiankatz** [comment]
@Julienh, glad to help. Please let us know if you run into any problems with the functionality -- I use only a small part of this library, and I suspect that some of the components haven't been tested against real live Amazon infrastructure in a while.
