### ISSUE TITLE
ZF3 port for this package?

### ISSUE THREAD

**Issue by bulbil** [zendframework/ZendService_Amazon#76]
I was curious whether there were plans to port this package to ZF3. I regularly build with a CMS based on ZF which recently upgraded from 2 to 3. Would love to have assets stored on S3 as seamlessly as before.

If there aren't plans, would be happy to contribute to the extent that I'm able.

Thanks!

**Comment by weierophinney** [comment]
This should work fine in ZF3; it has no specific integrations with the MVC framework, so you only need to instantiate the appropriate classes.

That said, I'd recommend using the official AWS PHP SDK instead, as it gets updated whenever there are API changes.
