### ISSUE TITLE
Travis is not active 

### ISSUE THREAD

**Issue by webimpress** [zendframework/ZendService_Amazon#78]
I've created PR with PHP 7.3 support but the build on travis didn't start.
I've checked on travis website and I've got:

![image](https://user-images.githubusercontent.com/7423207/50043362-9e11a280-006a-11e9-9e44-6f66c007ae26.png)

https://travis-ci.org/zendframework/ZendService_Amazon

**Comment by weierophinney** [comment]
Fixed. I think this is due to GitHub's migration from services to apps; my guess is we'll start seeing more of these issues crop up.

**Comment by webimpress** [comment]
@weierophinney thanks a lot !
